version: "3"
services:
  apache:
    build: './apache-php72/'
    volumes:
      - ./projeto/:/var/www/html/
    ports:
      - "5000:80"
    depends_on:
      - mysql
    networks:
      - frontend
      - backend
  mysql:
    image: mysql:5.7.20
    volumes:
      - "db_data:/var/lib/mysql"
      - "./mysql/initial_data:/docker-entrypoint-initdb.d"
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - backend
  composer:
    build: './composer/'
    volumes:
      - ./projeto/:/app
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  db_data:
